import seaborn as sns
import matplotlib.pyplot as plt
df = sns.load_dataset('tips')
df = df.dropna()
print(df.head())
sns.barplot(x='day', y='total_bill', hue='sex', data=df)
plt.title('Average Total Bill per Day by Gender')
plt.xlabel('Day')
plt.ylabel('Average Bill ($)')
plt.show()
sns.countplot(x='day', hue='sex', data=df)
plt.title('Number of Diners per Day by Gender')
plt.xlabel('Day')
plt.ylabel('Count')
plt.show()