file_read= open('lessonactivity\Codingal.txt', 'r')
print("File in Read Mode-")
print(file_read.read())
file_read.close()
file_write= open('lessonactivity\Codingal.txt', 'w')
file_write.write("File in Write Mode-")
file_write.write("Hi i am Penguin. I am 2 year old")
file_write.close()
file_append= open('lessonactivity\Codingal.txt', 'a')
file_append.write("\n File in append mode")
file_append.write("Hi i am penguin. I am 2 year old")
file_append.close()
