
f1= open('lessonactivity\Codingal.txt', 'r')
f2= open('lessonactivity\sample_doc (1).txt', 'r')
print('content of the first file before appending -\n', f1.read())
print('content of the second file before appending -\n', f2.read())
f1.close()
f2.close()
f1= open('lessonactivity\Codingal.txt', 'a+')
f2= open('lessonactivity\sample_doc (1).txt', 'r')
f1.write(f2.read())
f1.seek(0)
f2.seek(0)
print('content of the lessonactivity\Codingal.txt after appending -\n', f1.read())
print('content of the lessonactivity\sample_doc (1).txt after appending -\n', f2.read())
