file= open('lessonactivity\Codingal.txt', 'r')
print(file.read())
file.close()
file= open('lessonactivity\Codingal.txt', 'r')
print("\n Read in parts \n")
print(file.read(8))
file.close()
file= open('lessonactivity\Codingal.txt', 'a')
file.write= ("Hi , i am a penguin and am 1 year old")
file.close()